### ISSUE TITLE
Fix the pause/unpause audio context error shit.

### ISSUE THREAD

**Issue by Saltallica** [skepticalmartyr/PaperGorillas#51]
do it

**Comment by skepticalmartyr** [comment]
This is a Chrome bug.

https://bugs.chromium.org/p/chromium/issues/detail?id=593273

It happens when you all play and pause rapidly. it's not fixed yet.

**Comment by skepticalmartyr** [comment]
After taking another look at this, realized the root cause was a duration of less than 0 being passed in bufferSource.start in Howler. We are now setting duration to 0 if duration is less than 0 to stop the cascade of errors. Tested multiple times before/after patch. Before patch the error would appear regularly. After the patch I was unable to produce the error.
